import {Dimensions, PixelRatio, Platform, StyleSheet} from 'react-native';
import {colors, constants} from '../../../../config';

export default StyleSheet.create({
  safeContainer: {
    flex: 1,
    backgroundColor: colors.WHITE,
  },
  container: {
    flex: 1,
    backgroundColor: colors.WHITE,
  },
  scrollContainer: {},
  logo: {
    alignSelf: 'center',
  },
  subContainer: {
    width: '100%',
    marginTop: 10,
  },
  description: {
    fontFamily: constants.DEFAULT_FONT,
    fontSize: 16,
    margin: 10,
    marginHorizontal: 15,
  },
  inputText: {
    alignSelf: 'center',
    marginTop: 8,
    marginLeft: 8,
    marginRight: 8,
    marginBottom: 0,
    width: '92%',
    height: 53,
    zIndex: 1,
    backgroundColor: colors.WHITE,
    borderColor: colors.LIGHT_ALOE_TF,
    borderWidth: 3,
    borderRadius: 14,
    padding: 5,
    paddingLeft: 10,
    paddingRight: 10,
    fontFamily: constants.DEFAULT_FONT,
    fontSize: 17,
    color: colors.DARK_ALOE_TF,
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 0.5},
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 0.2,
  },
  emailText: {},
  errorText: {
    fontSize: 14,
    color: colors.RED_TF,
    marginLeft: 8,
  },
  confirmEmailText: {},
  hasNoEmailButton: {
    marginHorizontal: 5,
    marginTop: 15,
  },
  hasNoEmailButtonText: {
    fontFamily: constants.DEFAULT_FONT,
    fontSize: 14,
    color: colors.DARK_ALOE_TF,
    padding: 0,
    textAlign: 'center',
  },
  bottomMargin: {
    width: '100%',
    height: 10,
    marginBottom: 150,
  },
  buttonContainer: {
    width: '100%',
    height: 110,
    justifyContent: 'flex-start',
    alignItems: 'center',
    position: 'absolute',
    top:
      Dimensions.get('window').height -
      Platform.select({ios: 250, android: 200}),
    backgroundColor: colors.WHITE,
  },
  button: {
    marginBottom: 0,
    marginVertical: 2,
  },
  notNowButton: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.LIGHT_SILVER,
    marginBottom: 15,
  },
  notNowButtonText: {
    fontFamily: constants.DEFAULT_FONT_BOLD,
    color: colors.DARK_ALOE_TF,
  },
  continueButton: {
    marginTop: 10,
    marginBottom: 3,
  },
  continueButtonText: {
    fontFamily: constants.DEFAULT_FONT_BOLD,
    color: colors.WHITE,
    fontSize: 18,
  },
  graduationStudyTown: {
    marginTop: 10,
    marginHorizontal: 5,
    alignSelf: 'center',
    width: '92%',
    zIndex: 1,
    paddingLeft: 10,
    paddingRight: 10,
    fontSize: 17,
    fontFamily: constants.DEFAULT_FONT,
    backgroundColor: colors.WHITE,
    borderRadius: 14,
    borderColor: colors.WHITE,
    borderWidth: 0,
    shadowColor: colors.lightGray,
    shadowOpacity: 0.7,
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 5,
    elevation: 0.7,
  },
  overlayContainer: {
    backgroundColor: 'transparent',
  },
  overlay: {
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
    backgroundColor: colors.DEFAULT_BACKGROUND,
    height: 200,
    justifyContent: 'space-around',
    alignItems: 'center',
    padding: 0,
  },
  overlayLogo: {
    width: 90,
    height: 90,
  },
  overlayText: {
    fontSize: 15,
    fontFamily: constants.DEFAULT_FONT,
    textAlign: 'center',
  },
  overlayMain: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 2,
  },
  overlayHeader: {
    width: '100%',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  overlayHeaderText: {
    alignSelf: 'center',
  },
  overlayHeaderButton: {
    position: 'absolute',
    right: 5,
    zIndex: 10,
    width: 50,
    height: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  overlayHeaderButtonText: {
    alignSelf: 'center',
    fontWeight: 'bold',
    color: colors.DODGER_BLUE,
  },
  overlayList: {},
  overlayListItem: {
    height: 40,
    marginBottom: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomColor: colors.SILVER,
    borderBottomWidth: 1.5 / PixelRatio.get(),
    marginLeft: 10,
    marginRight: 15,
  },
  overlayListItemText: {
    marginLeft: 5,
  },
  overlayCheckIcon: {
    width: 15,
    height: 15,
    marginRight: 5,
  },
});
