import { Dimensions, Platform, StyleSheet } from "react-native";
import { colors, constants } from "../../../../config";

export default StyleSheet.create({
  safeContainer: {
    ...(Platform.OS === 'android'
      ? {flex: 1, height: Dimensions.get('window').height - 70}
      : {flex: 1}),
  },
  container: {
    flex: 1,
    backgroundColor: colors.DEFAULT_BACKGROUND,
  },
  scrollContainer: {},
  subContainer: {
    marginTop: 0,
    width: '100%',
    alignSelf: 'center',
  },
  logo: {
    alignSelf: 'center',
  },
  description: {
    fontFamily: constants.DEFAULT_FONT,
    fontSize: 16,
    margin: 10,
    marginHorizontal: 15,
  },
  cardContainer: {
    justifyContent: 'center',
    height: 50,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 14,
    fontSize: 17,
    marginHorizontal: 5,
    marginTop: 8,
    borderColor: colors.SILVER,
    backgroundColor: colors.WHITE,
    fontFamily: constants.DEFAULT_FONT,
    color: colors.lightGray,
    alignSelf: 'center',
    marginLeft: 8,
    marginRight: 8,
    marginBottom: 0,
    width: '92%',
    zIndex: 1,
    padding: 5,
    paddingLeft: 10,
    paddingRight: 10,
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 0.5},
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 0.2,
  },
  cardText: {
    fontFamily: constants.DEFAULT_FONT,
    fontSize: 17,
    borderColor: colors.LIGHT_SILVER,
    backgroundColor: colors.WHITE,
    color: colors.DEFAULT_PLACEHOLDER,
  },
  cardTextUploaded: {
    color: colors.THEFACULTY,
  },
  cardButton: {
    width: 26,
    height: 26,
    position: 'absolute',
    right: 15,
    top: 12,
  },
  uploadingIcon: {
    top: 2,
    right: -3,
  },
  cameraImage: {
    width: 25,
    height: 25,
  },
  universityText: {
    fontFamily: constants.DEFAULT_FONT,
    color: colors.BLACK,
    marginTop: 35,
  },
  graduationStudyTown: {
    marginTop: 10,
    marginHorizontal: 5,
    alignSelf: 'center',
    marginLeft: 8,
    marginRight: 8,
    marginBottom: 0,
    width: '92%',
    height: 50,
    zIndex: 1,
    backgroundColor: colors.WHITE,
    borderColor: colors.SILVER,
    borderRadius: 14,
    paddingLeft: 10,
    paddingRight: 10,
    fontSize: 17,
    fontFamily: constants.DEFAULT_FONT,
    borderWidth: StyleSheet.hairlineWidth,
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 0.5},
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 0.2,
  },
  buttonContainer: {
    width: '100%',
    height: 175,
    justifyContent: 'flex-start',
    alignItems: 'center',
    position: 'absolute',
    top:
      Dimensions.get('window').height -
      Platform.select({ios: 230, android: 190}),
    backgroundColor: colors.DEFAULT_BACKGROUND,
  },
  button: {
    marginBottom: 0,
    marginVertical: 2,
  },
  notNowButton: {
    backgroundColor: 'transparent',
    marginTop: 10,
    marginBottom: 7,
  },
  notNowButtonText: {
    color: colors.THEFACULTY,
  },
  continueButton: {
    marginBottom: 15,
  },
  universitySelectButton: {
    width: '92%',
    height: 50,
    marginTop: 10,
    alignSelf: 'center',
    justifyContent: 'center',
    borderColor: colors.SILVER,
    borderWidth: StyleSheet.hairlineWidth,
    backgroundColor: colors.WHITE,
    borderRadius: 14,
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 0.5},
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 0.2,
  },
  universitySelectButtonText: {
    fontSize: 17,
    fontFamily: constants.DEFAULT_FONT,
    paddingLeft: 10,
    color: colors.BLACK,
  },
  universitySelectButtonTextGray: {
    color: colors.DEFAULT_PLACEHOLDER,
  },
});
