/**
 * HomeScreen related style
 */
import { StyleSheet } from "react-native";
import constants from "../../config/constants";
import colors from "../../config/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: colors.DEFAULT_BACKGROUND,
  },
  safeArea: {
    backgroundColor: colors.DEFAULT_BACKGROUND,
  },
  logo: {
    flex: 1,
    width: '100%',
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  containerRow: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    width: 'auto',
    flex: 1,
    padding: 12,
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  rowTitle: {
    fontWeight: '600',
    fontFamily: constants.DEFAULT_FONT,
    marginLeft: 12,
    fontSize: 17,
  },
  rowText: {
    fontWeight: 'normal',
    fontFamily: constants.DEFAULT_FONT,
    marginLeft: 12,
    fontSize: 15,
  },
  rowUserImage: {
    height: 65,
    width: 65,
    borderRadius: 100,
  },
  imageFriendsTop: {
    height: 65,
    width: 65,
  },
  counterRow: {
    backgroundColor: colors.GREEN,
    borderRadius: 18,
    height: 66,
    width: 'auto',
    flex: 1,
    padding: 12,
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchContainer: {
    position: 'absolute',
    top: 0,
    paddingTop: 20,
    width: '100%',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.DEFAULT_BACKGROUND,
    backgroundColor: 'white',
  },
  carosuelTitle: {
    color: colors.BLACK,
    fontSize: 13,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  viewTest: {
    flexDirection: 'row',
    width: 335,
    height: 130,
    borderRadius: 18,
    marginTop: 10,
  },
  viewTest2: {
    width: 335,
    height: 130,
    backgroundColor: colors.PURPLE_TF,
    borderRadius: 18,
    flexDirection: 'column',
    marginTop: 10,
  },
  flap_image: {
    marginLeft: -1,
    width: 105,
    height: 130,
    resizeMode: 'contain',
    alignItems: 'center',
    justifyContent: 'center',
  },
  partner_logo: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
  },
  arrow_right: {
    width: 30,
    height: 30,
    right: 15,
    top: 15,
    position: 'absolute',
    flexDirection: 'row',
  },
  box_title: {
    marginTop: 15,
    marginLeft: 15,
    marginRight: 15,
    fontWeight: 'bold',
    fontFamily: constants.DEFAULT_FONT,
    color: colors.WHITE,
    fontSize: 24,
    width: '38%',
  },
  box_text: {
    marginTop: 5,
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 15,
    fontWeight: 'normal',
    fontFamily: constants.DEFAULT_FONT,
    color: colors.WHITE,
    fontSize: 16,
    flexWrap: 'wrap',
    width: '38%',
  },
});
