/**
 * FriendsScreen related style
 */
import { StyleSheet } from "react-native";
import constants from "../../config/constants";
import colors from "../../config/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  safeArea: {
    backgroundColor: colors.DEFAULT_BACKGROUND,
    flex: 1,
  },
  logo: {
    flex: 1,
    width: '100%',
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  containerRow_first: {
    backgroundColor: '#66B449',
    borderRadius: 13,
    width: 'auto',
    height: 110,
    padding: 0,
    marginTop: 8,
    marginLeft: 8,
    marginRight: 8,
    marginBottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  containerRow_second: {
    backgroundColor: '#66B449',
    borderRadius: 13,
    width: 'auto',
    height: 50,
    padding: 0,
    marginTop: 8,
    marginLeft: 8,
    marginRight: 8,
    marginBottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  image_first: {
    resizeMode: 'contain',
    height: 72,
    width: 72,
    margin: 20,
  },
  rowText_third: {
    fontWeight: 'normal',
    fontFamily: constants.DEFAULT_FONT,
    marginLeft: 15,
    marginTop: 30,
    marginBottom: 10,
    fontSize: 17,
  },
  textInput: {
    height: 47,
    backgroundColor: colors.WHITE,
    borderColor: colors.SILVER,
    borderRadius: 6,
    padding: 5,
    fontSize: 17,
    fontFamily: constants.DEFAULT_FONT,
    borderWidth: StyleSheet.hairlineWidth,
    marginBottom: 0,
    marginTop: 5,
    marginLeft: 8,
    marginRight: 8,
  },
  rowTitle_top: {
    fontFamily: constants.DEFAULT_FONT_BOLD,
    fontWeight: '700',
    marginLeft: 0,
    marginRight: 15,
    color: colors.WHITE,
    fontSize: 40,
    flex: 1,
    textAlign: 'center',
  },
  rowText_top: {
    fontFamily: constants.DEFAULT_FONT,
    fontWeight: 'normal',
    marginLeft: 15,
    fontSize: 17,
  },
  imageFriendsTop: {
    height: 65,
    width: 65,
  },
  counterRow: {
    backgroundColor: colors.GREEN,
    borderRadius: 18,
    height: 66,
    width: 'auto',
    flex: 1,
    padding: 12,
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchContainer: {
    position: 'absolute',
    top: 0,
    paddingTop: 20,
    width: '100%',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.DEFAULT_BACKGROUND,
    backgroundColor: 'white',
  },
});
