import {StyleSheet} from 'react-native';
import {colors, constants} from '../../config';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.WHITE,
    justifyContent: 'center',
    height: 400,
  },
  camera: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  takePictureButtonContainer: {
    height: 80,
    paddingTop: 15,
    width: '100%',
    justifyContent: 'space-around',
    alignItems: 'center',
    flexDirection: 'column',
    backgroundColor: colors.WHITE,
  },
  takePictureButton: {},
  takePictureButtonText: {
    fontFamily: constants.DEFAULT_FONT_BOLD,
    color: colors.WHITE,
    fontSize: 18,
    textAlign: 'center',
  },
  headerBox: {
    position: 'absolute',
    top: 20,
    width: '90%',
    height: 100,
    marginHorizontal: 0,
    alignSelf: 'center',
    borderRadius: 18,
    backgroundColor: colors.WHITE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerBoxText: {
    width: '100%',
    alignSelf: 'center',
    textAlign: 'center',
    fontSize: 14,
    color: colors.LIGHT_ALOE_TF,
    paddingHorizontal: 15,
    fontFamily: constants.DEFAULT_FONT,
  },
  headerBoxText2: {
    width: '100%',
    alignSelf: 'center',
    textAlign: 'center',
    fontSize: 14,
    color: colors.DARK_ALOE_TF,
    paddingHorizontal: 15,
    fontFamily: constants.DEFAULT_FONT_BOLD,
  },
  readBarcodeText: {
    height: 60,
    fontFamily: constants.DEFAULT_FONT_MEDIUM,
    color: colors.WHITE,
    fontSize: 25,
    letterSpacing: 1,
    textAlign: 'center',
  },
});
