import { Dimensions, PixelRatio, Platform, StyleSheet } from "react-native";
import { colors, constants } from "../../config";

export default StyleSheet.create({
  safeContainer: {
    ...(Platform.OS === 'android'
      ? {flex: 1, height: Dimensions.get('window').height - 70}
      : {flex: 1}),
  },
  container: {
    flex: 1,
    backgroundColor: colors.DEFAULT_BACKGROUND,
  },
  scrollContainer: {},
  subContainer: {
    flex: 1,
    marginTop: 0,
    width: '100%',
    alignSelf: 'center',
  },
  logo: {
    alignSelf: 'center',
  },
  description: {
    fontFamily: constants.DEFAULT_FONT,
    fontSize: 16,
    margin: 10,
    marginHorizontal: 15,
  },
  inputText: {
    alignSelf: 'center',
    marginTop: 8,
    marginLeft: 8,
    marginRight: 8,
    marginBottom: 0,
    width: '92%',
    height: 50,
    zIndex: 1,
    backgroundColor: colors.WHITE,
    borderColor: colors.SILVER,
    borderRadius: 14,
    padding: 5,
    paddingLeft: 10,
    paddingRight: 10,
    fontSize: 17,
    fontFamily: constants.DEFAULT_FONT,
    borderWidth: StyleSheet.hairlineWidth,
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 0.5},
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 0.2,
  },
  cardContainer: {
    justifyContent: 'center',
    height: 50,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 14,
    fontSize: 17,
    marginHorizontal: 5,
    marginTop: 8,
    borderColor: colors.SILVER,
    backgroundColor: colors.WHITE,
    fontFamily: constants.DEFAULT_FONT,
    color: colors.lightGray,
    alignSelf: 'center',
    marginLeft: 8,
    marginRight: 8,
    marginBottom: 0,
    width: '92%',
    zIndex: 1,
    padding: 5,
    paddingLeft: 10,
    paddingRight: 10,
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 0.5},
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 0.2,
  },
  cardText: {
    fontFamily: constants.DEFAULT_FONT,
    fontSize: 16,
    borderColor: colors.LIGHT_SILVER,
    backgroundColor: colors.WHITE,
    color: colors.lightGray,
  },
  cardTextUploaded: {
    color: colors.THEFACULTY,
  },
  cardButton: {
    width: 26,
    height: 26,
    position: 'absolute',
    right: 15,
    top: 12,
  },
  uploadingIcon: {
    top: 2,
    right: -3,
  },
  cameraImage: {
    width: 25,
    height: 25,
  },
  universityText: {
    fontFamily: constants.DEFAULT_FONT,
    color: colors.BLACK,
    marginTop: 35,
  },
  graduationStudyTown: {
    marginTop: 10,
    marginHorizontal: 5,
    alignSelf: 'center',
    marginLeft: 8,
    marginRight: 8,
    marginBottom: 0,
    width: '92%',
    height: 50,
    zIndex: 1,
    backgroundColor: colors.WHITE,
    borderColor: colors.SILVER,
    borderRadius: 14,
    paddingLeft: 10,
    paddingRight: 10,
    fontSize: 17,
    fontFamily: constants.DEFAULT_FONT,
    borderWidth: StyleSheet.hairlineWidth,
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 0.5},
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 0.2,
  },
  buttonContainer: {
    width: '100%',
    height: 175,
    justifyContent: 'flex-start',
    alignItems: 'center',
    position: 'absolute',
    top:
      Dimensions.get('window').height -
      Platform.select({ios: 230, android: 190}),
    backgroundColor: colors.DEFAULT_BACKGROUND,
  },
  button: {
    marginBottom: 0,
    marginVertical: 2,
  },
  notNowButton: {
    backgroundColor: 'transparent',
    marginTop: 10,
    marginBottom: 7,
  },
  notNowButtonText: {
    color: colors.THEFACULTY,
  },
  continueButton: {
    marginBottom: 15,
  },
  overlayContainer: {
    backgroundColor: 'transparent',
  },
  overlay: {
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
    backgroundColor: colors.DEFAULT_BACKGROUND,
    height: 200,
    justifyContent: 'space-around',
    alignItems: 'center',
    padding: 0,
  },
  overlayLogo: {
    width: 90,
    height: 90,
  },
  overlayText: {
    fontSize: 15,
    fontFamily: constants.DEFAULT_FONT,
    textAlign: 'center',
  },
  overlayMain: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 2,
  },
  overlayHeader: {
    width: '100%',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  overlayHeaderText: {
    alignSelf: 'center',
  },
  overlayHeaderButton: {
    position: 'absolute',
    right: 5,
    zIndex: 10,
    width: 50,
    height: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  overlayHeaderButtonText: {
    alignSelf: 'center',
    fontWeight: 'bold',
    color: colors.DODGER_BLUE,
  },
  overlayList: {},
  overlayListItem: {
    height: 40,
    marginBottom: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomColor: colors.SILVER,
    borderBottomWidth: 1.5 / PixelRatio.get(),
    marginLeft: 10,
    marginRight: 15,
  },
  overlayListItemText: {
    marginLeft: 5,
  },
  overlayCheckIcon: {
    width: 15,
    height: 15,
    marginRight: 5,
  },
});
