//deleteFile(FIREBASE_CONFIG.ORIGIN.IOS);
// copyFile(FIREBASE_CONFIG.PROD.IOS, FIREBASE_CONFIG.ORIGIN.IOS);

// deleteFile(FIREBASE_CONFIG.ORIGIN.ANDROID);
// copyFile(FIREBASE_CONFIG.PROD.ANDROID, FIREBASE_CONFIG.ORIGIN.ANDROID);

// deleteFile(SOURCE_CONFIG.ORIGIN);
// copyFile(SOURCE_CONFIG.PROD, SOURCE_CONFIG.ORIGIN);

// deleteFile(BUILD_CONFIG.ORIGIN.IOS);
// copyFile(BUILD_CONFIG.PROD.IOS, BUILD_CONFIG.ORIGIN.IOS);

// deleteFile(BUILD_CONFIG.ORIGIN.ANDROID);
// copyFile(BUILD_CONFIG.PROD.ANDROID, BUILD_CONFIG.ORIGIN.ANDROID);
