// deleteFile(FIREBASE_CONFIG.ORIGIN.IOS);
// copyFile(FIREBASE_CONFIG.TEST.IOS, FIREBASE_CONFIG.ORIGIN.IOS);

// deleteFile(FIREBASE_CONFIG.ORIGIN.ANDROID);
// copyFile(FIREBASE_CONFIG.TEST.ANDROID, FIREBASE_CONFIG.ORIGIN.ANDROID);

// deleteFile(SOURCE_CONFIG.ORIGIN);
// copyFile(SOURCE_CONFIG.TEST, SOURCE_CONFIG.ORIGIN);

// deleteFile(BUILD_CONFIG.ORIGIN.IOS);
// copyFile(BUILD_CONFIG.TEST.IOS, BUILD_CONFIG.ORIGIN.IOS);

// deleteFile(BUILD_CONFIG.ORIGIN.ANDROID);
// copyFile(BUILD_CONFIG.TEST.ANDROID, BUILD_CONFIG.ORIGIN.ANDROID);
