import { StyleSheet } from "react-native";
import { colors, constants } from "../../../../config";

export default StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
  },
  headerContainer: {
    width: '100%',
    height: '12%',
  },
  userScoreContainer: {
    marginLeft: 20,
    width: 130,
    height: 60,
    justifyContent: 'center',
    paddingLeft: 12,
    paddingRight: 5,
    zIndex: 205,
    elevation: 205,
  },
  hatIcon: {
    position: 'absolute',
    width: 50,
    height: 50,
    zIndex: 10,
    elevation: 10,
  },
  scoreView: {
    height: 40,
    borderRadius: 16,
    backgroundColor: colors.WHITE,
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.1,
    shadowRadius: 6,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  scoreText: {
    marginTop: 3,
    marginRight: 10,
    fontSize: 24,
    fontFamily: 'Kalam-Bold',
    color: colors.ORANGE_TF,
    width: 62,
    textAlign: 'center',
  },

  positionContainer: {
    position: 'absolute',
    right: 20,
    width: 130,
    height: 60,
    justifyContent: 'center',
    paddingRight: 12,
    paddingLeft: 5,
  },
  rankIcon: {
    position: 'absolute',
    right: 0,
    width: 50,
    height: 50,
    zIndex: 10,
    elevation: 10,
    alignItems: 'center',
  },
  globeIcon: {
    marginTop: 10.5,
    width: 20,
    height: 20,
    zIndex: 10,
    elevation: 10,
  },
  positionView: {
    height: 40,
    borderRadius: 16,
    backgroundColor: colors.WHITE,
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.1,
    shadowRadius: 6,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  positionText: {
    left: 5,
    fontSize: 20,
    fontFamily: constants.DEFAULT_FONT_BOLD,
    color: colors.BESTOF2.BG1,
    width: 62,
    textAlign: 'center',
  },

  gameCardsContainer: {
    justifyContent: 'space-around',
    alignItems: 'center',
    height: '86%',
  },
  gameCardContainer: {
    width: '80%',
    height: '30%',
    minHeight: 105,
    maxHeight: 120,
    borderRadius: 15,
    backgroundColor: colors.WHITE,
    shadowColor: colors.lightGray,
    shadowOpacity: 0.3,
    shadowOffset: {width: 0, height: 0},
    shadowRadius: 10,
    elevation: 8,
    transform: [{perspective: 180}, {rotateX: '-2deg'}],
    zIndex: 100,
  },
  gameCardIcon: {
    marginTop: 13,
    marginLeft: 23,
    width: '20%',
    height: '100%',
  },
  gameCardText: {
    paddingTop: 28,
    width: '50%',
    fontFamily: constants.DEFAULT_FONT,
    fontSize: 14,
    lineHeight: 16,
    color: colors.BESTOF2.BG1,
    marginLeft: 20,
  },
  gameCardButton: {
    position: 'absolute',
    bottom: -20,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 17,
    height: '41%',
    minHeight: 45,
    backgroundColor: colors.BESTOF2.BG1,
    paddingHorizontal: 15,
  },
  gameCardButtonText: {
    fontFamily: constants.DEFAULT_FONT_BOLD,
    fontSize: 20,
    color: colors.WHITE,
  },

  rankingPopoverContainer: {
    position: 'absolute',
    top: 58,
    right: 15,
    backgroundColor: colors.DEFAULT_BACKGROUND,
    padding: 16,
    width: 320,
    borderRadius: 16,
    shadowColor: '#777',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.4,
    shadowRadius: 6,
    zIndex: 200,
    elevation: 200,
  },
  avgPopoverContainer: {
    position: 'absolute',
    top: 58,
    left: 15,
    backgroundColor: colors.DEFAULT_BACKGROUND,
    padding: 15,
    width: 320,
    borderRadius: 16,
    shadowColor: '#777',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.4,
    shadowRadius: 6,
    zIndex: 2000,
    elevation: 2000,
  },
  alreadyPlayingPopoverContainer: {
    position: 'absolute',
    top: -40,
    alignSelf: 'center',
    backgroundColor: colors.DEFAULT_BACKGROUND,
    padding: 15,
    width: 320,
    borderRadius: 16,
    shadowColor: '#777',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.4,
    shadowRadius: 6,
    zIndex: 2000,
    elevation: 2000,
  },
  popoverTextStyle: {
    color: colors.BESTOF2.BG1,
    fontSize: 16,
    textAlign: 'center',
    fontFamily: constants.DEFAULT_FONT,
  },
});
