import { StyleSheet } from "react-native";
import { colors, constants } from "../../../../config";

export default StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
  },
  header: {
    width: '100%',
    alignItems: 'center',
  },
  infoTitle: {
    fontSize: 24,
    color: colors.BESTOF2.BG1,
    fontFamily: constants.DEFAULT_FONT_BOLD,
    marginBottom: 5,
  },
  infoText: {
    width: '90%',
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 20.8,
    color: colors.BESTOF2.BG1,
    fontFamily: constants.DEFAULT_FONT,
    marginBottom: 25,
  },
  averageText: {
    height: 40,
    minWidth: 100,
    paddingHorizontal: 0,
    textAlign: 'center',
    borderRadius: 16,
    backgroundColor: colors.WHITE,
    justifyContent: 'center',
  },
  scoreText: {
    marginTop: 4,
    marginLeft: 43,
    fontSize: 24,
    marginRight: 10,
    fontFamily: 'Kalam-Bold',
    color: colors.ORANGE_TF,
    width: 62,
    textAlign: 'center',
  },
  missingBestOfsLabel: {
    marginLeft: 43,
    marginRight: 10,
    fontFamily: constants.DEFAULT_FONT,
    fontSize: 18,
    color: colors.BESTOF2.BG1,
  },
  filterContainer: {
    position: 'absolute',
    alignItems: 'flex-end',
    paddingRight: 20,
    width: 100,
    height: 75,
    right: 0,
  },
  filterIcon: {
    marginTop: 2,
    width: 25,
    height: 25,
    zIndex: 10,
    elevation: 10,
  },
  hatIcon: {
    marginLeft: 10,
    position: 'absolute',
    width: 25,
    height: 25,
    zIndex: 10,
    elevation: 10,
  },
  verticalLine: {
    height: 35,
    width: 12,
    backgroundColor: colors.WHITE,
  },
  invisibleSpace: {
    height: 15,
    width: 12,
  },
  endAverageCalculationContainer: {
    marginTop: 25,
    marginBottom: 15,
    height: 45,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  endAverageCalculationText: {
    marginHorizontal: 10,
    fontFamily: constants.DEFAULT_FONT,
    fontSize: 16,
    color: colors.WHITE,
  },
  horizontalLine: {
    width: '20%',
    height: 2,
    backgroundColor: colors.WHITE,
  },

  matchCardsContainer: {
    marginTop: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  matchCardContainer: {
    width: '85%',
    height: 196,
    borderRadius: 15,
    backgroundColor: 'transparent',
    elevation: 0,
    zIndex: 100,
  },
  matchCardContainerBG: {
    position: 'absolute',
    width: '100%',
    height: 200,
    borderRadius: 15,
    backgroundColor: colors.WHITE,
    shadowColor: colors.darkGray,
    shadowOpacity: 0.2,
    shadowOffset: {width: -5, height: -5},
    shadowRadius: 10,
    elevation: -4,
    transform: [{perspective: 180}, {rotateX: '-3deg'}],
    zIndex: -1,
  },
  matchCardIcon: {
    marginTop: 12,
    marginLeft: 23,
    width: 68,
    height: 68,
  },
  matchCardText: {
    marginTop: 30,
    width: '55%',
    fontFamily: constants.DEFAULT_FONT,
    fontSize: 13,
    color: colors.BESTOF2.BG1,
    marginLeft: 20,
  },
  matchCardButton: {
    position: 'absolute',
    bottom: -20,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    height: 50,
    backgroundColor: colors.BESTOF2.BG1,
    paddingHorizontal: 15,
  },
  matchCardButtonText: {
    fontFamily: constants.DEFAULT_FONT_BOLD,
    fontSize: 20,
    color: colors.WHITE,
  },
  wonOrLostLabel: {
    position: 'absolute',
    fontSize: 16,
    fontFamily: constants.DEFAULT_FONT_BOLD,
    top: 2,
    left: 18,
    width: 80,
  },
  finishDateLabel: {
    color: colors.BESTOF2.BG1,
    fontSize: 12,
    fontFamily: constants.DEFAULT_FONT_BOLD,
    textAlign: 'right',
  },
  timeView: {
    justifyContent: 'flex-end',
    position: 'absolute',
    flexDirection: 'row',
    top: 2,
    right: 10,
    width: 70,
  },
  profileImagesContainer: {
    width: '100%',
    justifyContent: 'center',
    height: 60,
    marginTop: 12,
    flexDirection: 'row',
    elevation: 1,
    zIndex: 100,
  },
  usersImageContainer: {
    marginHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    width: 60,
    height: 60,
  },
  user1Image: {
    width: 46,
    height: 46,
    borderRadius: 23,
  },
  user2Image: {
    width: 46,
    height: 46,
    borderRadius: 23,
  },
  crownImageUser1: {
    position: 'absolute',
    width: 53,
    height: 53,
    zIndex: 2,
    elevation: 1,
  },
  crownImageUser2: {
    position: 'absolute',
    width: 53,
    height: 53,
    zIndex: 2,
    elevation: 1,
  },
  smallHatIcon: {
    top: 2.5,
    marginRight: 5,
    width: 12,
    height: 12,
  },
  usersScoresContainer: {
    marginTop: 10,
    width: '100%',
    justifyContent: 'center',
    height: 60,
    flexDirection: 'row',
  },
  loggedUserScore: {
    marginTop: -15,
    color: colors.ORANGE_TF,
    fontSize: 20,
    marginRight: 35,
    fontFamily: 'Kalam-Bold',
  },
  opponentUserScore: {
    marginTop: -15,
    color: colors.ORANGE_TF,
    fontSize: 20,
    marginLeft: 35,
    fontFamily: 'Kalam-Bold',
  },
  scoreIcon: {
    position: 'absolute',
    marginTop: -12,
    width: 20,
    height: 20,
  },
  opponentDataContainer: {
    marginTop: -40,
  },
  opponentNickname: {
    color: colors.BESTOF2.BG1,
    fontSize: 22,
    fontFamily: constants.DEFAULT_FONT_BOLD,
    textAlign: 'center',
  },
  opponentFacultyName: {
    color: colors.BESTOF2.BG1,
    fontSize: 18,
    fontFamily: constants.DEFAULT_FONT,
    textAlign: 'center',
  },
  opponentUniversityName: {
    color: colors.LIGHT_ALOE_TF,
    fontSize: 14,
    fontFamily: constants.DEFAULT_FONT,
    textAlign: 'center',
  },
});
